my_robot_model:

  joint_state_controller:
      type: joint_state_controller/JointStateController
      publish_rate: 20

  right_wheel_hinge_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: right_wheel_hinge

  left_wheel_hinge_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: left_wheel_hinge

  right_wheel_2_hinge_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: right_wheel_2_hinge

  left_wheel_2_hinge_joint_velocity_controller:
      type: velocity_controllers/JointVelocityController
      joint: left_wheel_2_hinge

  camera_shaft_joint_position_controller:
      type: velocity_controllers/JointPositionController
      joint: camera_shaft_hinge
      pid: {p: 1.0, i: 1.0, d: 0.0}

  gazebo_ros_control:
      pid_gains:
        left_wheel_hinge: {p: 1.0, i: 1.0, d: 0.0}
        right_wheel_hinge: {p: 1.0, i: 1.0, d: 0.0}
        left_wheel_2_hinge: {p: 1.0, i: 1.0, d: 0.0}
        right_wheel_2_hinge: {p: 1.0, i: 1.0, d: 0.0}
        camera_shaft_hinge: {p: 1.0, i: 1.0, d: 0.0}
